bootrom-tools: supply UniPro MID/PID values in nuttx2ffff based on --build flag
For ES3 boards we need to flash all firmware in the form of a TFTF inside an
FFFF, which must have the correct UniPro MID/PID and Ara VID/PID values for the
chip which loads it.  Begin adding this functionality to nuttx2ffff, based on a
hardcoded assignment of UniPro MID/PID values to --build values, where builds
can be associated with multiple chips.  Also build separate TFTF and FFFF
packages for each chip.

Testing Done: ES3 FFFF's generated containing correctly identified TFTF's
Bug Number: SW-2252
Review URL: https://reviews.leaflabs.com/r/2488/
Reviewed by: Morgan Girling <girling_morgan@projectara.com>, Jun Li <li_jun@projectara.com>

Signed-off-by: Eli Sennesh <esennesh@leaflabs.com>

diff --git a/scripts/nuttx2ffff b/scripts/nuttx2ffff
--- a/scripts/nuttx2ffff
+++ b/scripts/nuttx2ffff
@@ -69,8 +69,9 @@ echo "Usage:
    --in      Arbitrary path to a nuttx file
    --build   Which nuttx image to use:
               ara-bridge-es2-debug-apbridgea | ara-bridge-es2-debug-generic |
-              (ara-svc-db3) | ara-bridge-es2-debug-bringup | ara-svc-bdb2a |
-              ara-svc-sdb
+              ara-bridge-es2-debug-bringup | ara-svc-bdb2a | ara-svc-sdb |
+              ara-svc-db3 | ara-bridge-es3-debug-apbridgea |
+              ara-bridge-es3-debug-generic
    If neither --in or --build are specified, it will use the image in
    .../nuttx/nuttx
 "
@@ -91,6 +92,26 @@ if [ ! ${NUTTX_IMAGE} ]; then
         echo "nuttx image from default"
     fi
 fi
+
+case ${nuttx_build} in
+    ara-bridge-es2-debug-apbridgea | ara-bridge-es2-debug-generic)
+        mids=(0x0126)
+        pids=(0x1000)
+        ;;
+    ara-bridge-es2-debug-bringup)
+        mids=(0x0126)
+        pids=(0x1000)
+        ;;
+    ara-bridge-es3-debug-apbridgea)
+        mids=(0x0126)
+        pids=(0x1001)
+        ;;
+    ara-bridge-es3-debug-generic)
+        mids=(0x0126 0x0126)
+        pids=(0x1001 0x1002)
+        ;;
+esac
+
 echo "Packaging ${NUTTX_IMAGE}"
 
 
@@ -103,43 +124,49 @@ fi
 #echo "Package ${NUTTX_IMAGE}/nuttx into nuttx.tftf:"
 #echo "start address: 0x$start"
 
-create-tftf \
-  $verbose \
-  --header-size 0x200 \
-  --type s2fw \
-  --name "NuttX S3FW-as-S2FW" \
-  --elf ${NUTTX_IMAGE} \
-  --out ${NUTTX_IMAGE}.tftf
+PATH=$(cd ..; pwd):$PATH
 
-if [[ $? != 0 ]]; then
-    echo "There were problems creating the TFTF"
-    exit 1
-fi
+for i in ${!mids[*]}; do
+    create-tftf \
+      $verbose \
+      --header-size 0x200 \
+      --type s2fw \
+      --name "NuttX S3FW-as-S2FW" \
+      --unipro-mfg=${mids[i]} \
+      --unipro-pid=${pids[i]} \
+      --elf ${NUTTX_IMAGE} \
+      --out ${NUTTX_IMAGE}.tftf
 
-create-ffff \
-  $verbose \
-  --header-size 0x1000 \
-  --generation 1  \
-  --flash-capacity 0x40000 \
-  --image-length 0x40000 \
-  --erase-size 0x800 \
-  --name "Nuttx test build" \
-  --s2f ${NUTTX_IMAGE}.tftf --eloc 0x2000 --egen 1 \
-  --out ${NUTTX_IMAGE}.ffff
+    if [[ $? != 0 ]]; then
+        echo "There were problems creating the TFTF"
+        exit 1
+    fi
+
+    create-ffff \
+      $verbose \
+      --header-size 0x1000 \
+      --generation 1  \
+      --flash-capacity 0x40000 \
+      --image-length 0x40000 \
+      --erase-size 0x800 \
+      --name "Nuttx test build" \
+      --s2f ${NUTTX_IMAGE}.tftf --eloc 0x2000 --egen 1 \
+      --out ${NUTTX_IMAGE}-${mids[i]}-${pids[i]}.ffff
 
 
-if [[ $? != 0 ]]; then
-    echo "There were problems creating the FFFF"
+    if [[ $? != 0 ]]; then
+        echo "There were problems creating the FFFF"
+        # Cleanup intermediate files
+        rm ${NUTTX_IMAGE}.tftf
+        exit 1
+    fi
+
+    # Resize the FFFF to the Flash
+    truncate -s 2M ${NUTTX_IMAGE}-${mids[i]}-${pids[i]}.ffff
+
     # Cleanup intermediate files
     rm ${NUTTX_IMAGE}.tftf
-    exit 1
-fi
-
-# Resize the FFFF to the Flash
-truncate -s 2M ${NUTTX_IMAGE}.ffff
-
-# Cleanup intermediate files
-rm ${NUTTX_IMAGE}.tftf
+done
 
 echo "Done"
 
